theme: jekyll-theme-cayman
show_downloads: true

lang: ja

title: Takumi Tanabe
description: 田邊拓実

collections:
  chapters:
    output: true

github:
  is_project_page: true
  repository_url: https://github.com/yoshinobc/yoshinobc.github.io
github_username: yoshinobc

exclude:
  - README.md
